name: health_4_all
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  validadores: ^1.0.9
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  uuid: ^3.0.6
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
